library(dplyr)
library(stringr)
library(readr)

THEME_GROUPS <- list(
  "sociodemographics" = c(
    "pct_age_18_24",
    "pct_age_25_34",
    "pct_age_35_44",
    "pct_age_45_54",
    "pct_age_55_64",
    "pct_age_65_74",
    "pct_age_75_older",
    "pct_condition_asthma",
    "pct_condition_cancer",
    "pct_condition_cvd",
    "pct_condition_diabetes",
    "pct_condition_hbp",
    "pct_condition_immune",
    "pct_condition_kidney",
    "pct_condition_lung",
    "pct_condition_none",
    "pct_condition_obesity",
    "pct_education_2yr_degree",
    "pct_education_4yr_degree",
    "pct_education_doctorate",
    "pct_education_highschool_or_equivalent",
    "pct_education_less_than_highschool",
    "pct_education_masters",
    "pct_education_professional_degree",
    "pct_education_some_college",
    "pct_gender_female",
    "pct_gender_male",
    "pct_gender_nonbinary_other",
    "pct_gender_unknown",
    "pct_hispanic_latino",
    "pct_language_home_chinese",
    "pct_language_home_english",
    "pct_language_home_french",
    "pct_language_home_other",
    "pct_language_home_portuguese",
    "pct_language_home_spanish",
    "pct_language_home_vietnamese",
    "pct_occ_4w_admin",
    "pct_occ_4w_arts",
    "pct_occ_4w_building",
    "pct_occ_4w_construction",
    "pct_occ_4w_education",
    "pct_occ_4w_food",
    "pct_occ_4w_health_prac",
    "pct_occ_4w_health_support",
    "pct_occ_4w_maintenance",
    "pct_occ_4w_other",
    "pct_occ_4w_personal",
    "pct_occ_4w_production",
    "pct_occ_4w_protective",
    "pct_occ_4w_sales",
    "pct_occ_4w_social",
    "pct_occ_4w_transportation",
    "pct_pregnant",
    "pct_race_american_indian_alaska_native",
    "pct_race_asian",
    "pct_race_black_african_american",
    "pct_race_native_hawaiian_pacific_islander",
    "pct_race_multiple_other",
    "pct_race_white",
    "pct_smoke",
    "pct_work_for_pay_4w",
    "pct_work_for_pay_outside_home_4w",
    "mean_adults_in_household",
    "mean_children_in_household",
    "mean_olderadults_in_household",
    "mean_ppl_in_household",
    "mean_ppl_in_household_adults",
    "mean_ppl_in_household_children",
    "mean_ppl_in_household_olderadults"
  ),
  "vaccines" = c(
    "pct_accept_vaccine",
    "pct_accept_vaccine_no_appointment",
    "pct_accept_vaccine_defno",
    "pct_accept_vaccine_defyes",
    "pct_accept_vaccine_no_appointment_defno",
    "pct_accept_vaccine_no_appointment_defyes",
    "pct_accept_vaccine_no_appointment_probno",
    "pct_accept_vaccine_no_appointment_probyes",
    "pct_accept_vaccine_probno",
    "pct_accept_vaccine_probyes",
    "pct_appointment_have",
    "pct_appointment_not_vaccinated",
    "pct_appointment_or_accept_vaccine",
    "pct_appointment_tried",
    "pct_barrier_allergic",
    "pct_barrier_cost",
    "pct_barrier_dislike_vaccines",
    "pct_barrier_dislike_vaccines_generally",
    "pct_barrier_distrust_govt",
    "pct_barrier_distrust_vaccines",
    "pct_barrier_dontneed",
    "pct_barrier_health_condition",
    "pct_barrier_ineffective",
    "pct_barrier_low_priority",
    "pct_barrier_not_recommended",
    "pct_barrier_other",
    "pct_barrier_pregnant",
    "pct_barrier_reason_allergic",
    "pct_barrier_reason_cost",
    "pct_barrier_reason_not_recommended",
    "pct_barrier_reason_dontbelieve",
    "pct_barrier_reason_dontlike",
    "pct_barrier_reason_distrust_gov",
    "pct_barrier_reason_health",
    "pct_barrier_reason_other",
    "pct_barrier_reason_otherpeople",
    "pct_barrier_reason_pregnant",
    "pct_barrier_reason_religion",
    "pct_barrier_reason_sideeffect",
    "pct_barrier_reason_distrust_vaccine",
    "pct_barrier_reason_wait",
    "pct_barrier_reason_wontwork",
    "pct_barrier_religious",
    "pct_barrier_sideeffects",
    "pct_barrier_wait_safety",
    "pct_defno_barrier_allergic",
    "pct_defno_barrier_cost",
    "pct_defno_barrier_dislike_vaccines",
    "pct_defno_barrier_dislike_vaccines_generally",
    "pct_defno_barrier_distrust_govt",
    "pct_defno_barrier_distrust_vaccines",
    "pct_defno_barrier_dontneed",
    "pct_defno_barrier_health_condition",
    "pct_defno_barrier_ineffective",
    "pct_defno_barrier_low_priority",
    "pct_defno_barrier_not_recommended",
    "pct_defno_barrier_other",
    "pct_defno_barrier_pregnant",
    "pct_defno_barrier_religious",
    "pct_defno_barrier_sideeffects",
    "pct_defno_barrier_wait_safety",
    "pct_defno_dontneed_reason_dont_spend_time",
    "pct_defno_dontneed_reason_had_covid",
    "pct_defno_dontneed_reason_not_beneficial",
    "pct_defno_dontneed_reason_not_high_risk",
    "pct_defno_dontneed_reason_not_serious",
    "pct_defno_dontneed_reason_other",
    "pct_defno_dontneed_reason_precautions",
    "pct_dontneed_reason_dont_spend_time",
    "pct_dontneed_reason_had_covid",
    "pct_dontneed_reason_not_beneficial",
    "pct_dontneed_reason_not_high_risk",
    "pct_dontneed_reason_not_serious",
    "pct_dontneed_reason_other",
    "pct_dontneed_reason_precautions",
    "pct_hesitant_barrier_allergic",
    "pct_hesitant_barrier_cost",
    "pct_hesitant_barrier_dislike_vaccines",
    "pct_hesitant_barrier_dislike_vaccines_generally",
    "pct_hesitant_barrier_distrust_govt",
    "pct_hesitant_barrier_distrust_vaccines",
    "pct_hesitant_barrier_dontneed",
    "pct_hesitant_barrier_health_condition",
    "pct_hesitant_barrier_ineffective",
    "pct_hesitant_barrier_low_priority",
    "pct_hesitant_barrier_not_recommended",
    "pct_hesitant_barrier_other",
    "pct_hesitant_barrier_pregnant",
    "pct_hesitant_barrier_religious",
    "pct_hesitant_barrier_sideeffects",
    "pct_hesitant_barrier_wait_safety",
    "pct_hesitant_dontneed_reason_dont_spend_time",
    "pct_hesitant_dontneed_reason_had_covid",
    "pct_hesitant_dontneed_reason_not_beneficial",
    "pct_hesitant_dontneed_reason_not_high_risk",
    "pct_hesitant_dontneed_reason_not_serious",
    "pct_hesitant_dontneed_reason_other",
    "pct_hesitant_dontneed_reason_precautions",
    "pct_hesitant_trust_covid_info_cdc",
    "pct_hesitant_trust_covid_info_doctors",
    "pct_hesitant_trust_covid_info_experts",
    "pct_hesitant_trust_covid_info_friends",
    "pct_hesitant_trust_covid_info_govt_health",
    "pct_hesitant_trust_covid_info_journalists",
    "pct_hesitant_trust_covid_info_politicians",
    "pct_hesitant_trust_covid_info_religious",
    "pct_hesitant_vaccine",
    "pct_hesitant_vaccine_likely_doctors",
    "pct_hesitant_vaccine_likely_friends",
    "pct_hesitant_vaccine_likely_govt",
    "pct_hesitant_vaccine_likely_local_health",
    "pct_hesitant_vaccine_likely_politicians",
    "pct_hesitant_vaccine_likely_who",
    "pct_hesitant_worried_vaccine_sideeffects",
    "pct_informed_access",
    "pct_initial_dose_one_of_one",
    "pct_initial_dose_one_of_two",
    "pct_initial_dose_two_of_two",
    "pct_receive_all_doses_noplan",
    "pct_receive_all_doses_plan",
    "pct_receive_all_doses_yes",
    "pct_received_2_vaccine_doses",
    "pct_trust_covid_info_cdc",
    "pct_trust_covid_info_doctors",
    "pct_trust_covid_info_experts",
    "pct_trust_covid_info_friends",
    "pct_trust_covid_info_govt_health",
    "pct_trust_covid_info_journalists",
    "pct_trust_covid_info_politicians",
    "pct_trust_covid_info_religious",
    "pct_vaccinate_children",
    "pct_child_vaccine_vaccinated_or_accept",
    "pct_vaccinated",
    "pct_vaccinated_appointment_or_accept",
    "pct_vaccinated_at_least_one_booster",
    "pct_vaccinated_booster_accept",
    "pct_vaccinated_booster_defno",
    "pct_vaccinated_booster_defyes",
    "pct_vaccinated_booster_hesitant",
    "pct_vaccinated_booster_probno",
    "pct_vaccinated_booster_probyes",
    "pct_vaccinated_no_booster",
    "pct_vaccinated_one_booster",
    "pct_vaccinated_or_accept",
    "pct_vaccinated_two_or_more_boosters",
    "pct_vaccine_barrier_appointment_location",
    "pct_vaccine_barrier_appointment_location_has",
    "pct_vaccine_barrier_appointment_location_tried",
    "pct_vaccine_barrier_appointment_time",
    "pct_vaccine_barrier_appointment_time_has",
    "pct_vaccine_barrier_appointment_time_tried",
    "pct_vaccine_barrier_childcare",
    "pct_vaccine_barrier_childcare_has",
    "pct_vaccine_barrier_childcare_tried",
    "pct_vaccine_barrier_document",
    "pct_vaccine_barrier_document_has",
    "pct_vaccine_barrier_document_tried",
    "pct_vaccine_barrier_eligible",
    "pct_vaccine_barrier_eligible_has",
    "pct_vaccine_barrier_eligible_tried",
    "pct_vaccine_barrier_language",
    "pct_vaccine_barrier_language_has",
    "pct_vaccine_barrier_language_tried",
    "pct_vaccine_barrier_no_appointments",
    "pct_vaccine_barrier_no_appointments_has",
    "pct_vaccine_barrier_no_appointments_tried",
    "pct_vaccine_barrier_none",
    "pct_vaccine_barrier_none_has",
    "pct_vaccine_barrier_none_tried",
    "pct_vaccine_barrier_other",
    "pct_vaccine_barrier_other_has",
    "pct_vaccine_barrier_other_tried",
    "pct_vaccine_barrier_technical_difficulties",
    "pct_vaccine_barrier_technical_difficulties_has",
    "pct_vaccine_barrier_technical_difficulties_tried",
    "pct_vaccine_barrier_technology_access",
    "pct_vaccine_barrier_technology_access_has",
    "pct_vaccine_barrier_technology_access_tried",
    "pct_vaccine_barrier_time",
    "pct_vaccine_barrier_time_has",
    "pct_vaccine_barrier_time_tried",
    "pct_vaccine_barrier_travel",
    "pct_vaccine_barrier_travel_has",
    "pct_vaccine_barrier_travel_tried",
    "pct_vaccine_barrier_type",
    "pct_vaccine_barrier_type_has",
    "pct_vaccine_barrier_type_tried",
    "pct_vaccine_likely_doctors",
    "pct_vaccine_likely_friends",
    "pct_vaccine_likely_govt_health",
    "pct_vaccine_likely_local_health",
    "pct_vaccine_likely_politicians",
    "pct_vaccine_likely_who",
    "pct_vaccine_timing_dontknow",
    "pct_vaccine_timing_morethansix",
    "pct_vaccine_timing_onemonth",
    "pct_vaccine_timing_sixmonths",
    "pct_vaccine_timing_threemonths",
    "pct_vaccine_timing_weeks",
    "pct_vaccine_tried",
    "pct_worried_vaccine_sideeffects",
    "pct_flu_shot_1y",
    "pct_flu_vaccine_july_2020",
    "pct_flu_vaccine_june_2020",
    "pct_flu_vaccinated_2021",
    "pct_overall_vaccine_hesitancy",
    "pct_overall_vaccine_hesitancy",
    "pct_vaccine_incomplete_allergic",
    "pct_vaccine_incomplete_cost",
    "pct_vaccine_incomplete_distrust_gov",
    "pct_vaccine_incomplete_distrust_vaccine",
    "pct_vaccine_incomplete_dontbelieve",
    "pct_vaccine_incomplete_dontlike",
    "pct_vaccine_incomplete_health",
    "pct_vaccine_incomplete_not_recommended",
    "pct_vaccine_incomplete_other",
    "pct_vaccine_incomplete_otherpeople",
    "pct_vaccine_incomplete_pregnant",
    "pct_vaccine_incomplete_religion",
    "pct_vaccine_incomplete_sideeffect",
    "pct_vaccine_incomplete_wait",
    "pct_vaccine_incomplete_wontwork"
  ),
  "symptoms_and_testing" = c(
    "pct_symp_anosmia",
    "pct_had_covid_ever",
    "pct_had_covid_ever",
    "pct_symp_sore_throat",
    "pct_cli",
    "pct_ever_tested",
    "pct_ever_tested_positive",
    "pct_hh_cmnty_cli",
    "pct_ili",
    "pct_test_reason_contact",
    "pct_test_reason_medical",
    "pct_test_reason_none",
    "pct_test_reason_required",
    "pct_test_reason_sick",
    "pct_test_reason_travel",
    "pct_test_reason_visit",
    "pct_test_reason_large_event",
    "pct_test_reason_crowd",
    "pct_tested_14d",
    "pct_tested_positive_14d",
    "pct_wanted_test_14d",
    "pct_cough_mucus",
    "mean_days_symptoms",
    "pct_hh_cmnty_cli",
    "pct_nohh_cmnty_cli",
    "mean_ppl_symptoms_community",
    "mean_ppl_symptoms_household",
    "pct_reason_not_tested_appointment",
    "pct_reason_not_tested_cost",
    "pct_reason_not_tested_location",
    "pct_reason_not_tested_stigma",
    "pct_reason_not_tested_time",
    "pct_reason_not_tested_travel",
    "pct_reason_not_tested_tried",
    "pct_reason_not_tested_none",
    "pct_taken_temp",
    "pct_symp_aches",
    "pct_symp_chest_pain",
    "pct_symp_chills",
    "pct_symp_cough",
    "pct_symp_diarrhea",
    "pct_symp_diff_breathing",
    "pct_symp_eye_pain",
    "pct_symp_fatigue",
    "pct_symp_fever",
    "pct_symp_headache",
    "pct_symp_nasal_congestion",
    "pct_symp_nausea",
    "pct_symp_none",
    "pct_symp_other",
    "pct_symp_runny_nose",
    "pct_symp_shortness_breath",
    "pct_symp_sleep_changes",
    "pct_symp_stuffy_nose",
    "pct_symp_unusual_given_fever",
    "pct_symp_unusual_given_cough",
    "pct_symp_unusual_given_shortness_breath",
    "pct_symp_unusual_given_diff_breathing",
    "pct_symp_unusual_given_fatigue",
    "pct_symp_unusual_given_nasal_congestion",
    "pct_symp_unusual_given_runny_nose",
    "pct_symp_unusual_given_aches",
    "pct_symp_unusual_given_sore_throat",
    "pct_symp_unusual_given_chest_pain",
    "pct_symp_unusual_given_nausea",
    "pct_symp_unusual_given_diarrhea",
    "pct_symp_unusual_given_anosmia",
    "pct_symp_unusual_given_other",
    "pct_symp_unusual_given_eye_pain",
    "pct_symp_unusual_given_chills",
    "pct_symp_unusual_given_headache",
    "pct_symp_unusual_given_sleep_changes",
    "pct_symp_unusual_given_stuffy_nose",
    "pct_unusual_symptom_fever",
    "pct_unusual_symptom_cough",
    "pct_unusual_symptom_shortness_breath",
    "pct_unusual_symptom_breathing",
    "pct_unusual_symptom_tired",
    "pct_unusual_symptom_congestion",
    "pct_unusual_symptom_runnynose",
    "pct_unusual_symptom_muscle",
    "pct_unusual_symptom_sorethroat",
    "pct_unusual_symptom_chestpain",
    "pct_unusual_symptom_nausea",
    "pct_unusual_symptom_diarrhea",
    "pct_unusual_symptom_anosmia",
    "pct_unusual_symptom_eyepain",
    "pct_unusual_symptom_chills",
    "pct_unusual_symptom_headache",
    "pct_unusual_symptom_sleep_changes",
    "pct_unusual_symptom_stuffy_nose",
    "pct_unusual_symptom_other",
    "pct_unusual_symptom_hospital",
    "pct_unusual_symptom_hospital_tried",
    "pct_unusual_symptom_medical_care_called_doctor",
    "pct_unusual_symptom_medical_care_telemedicine",
    "pct_unusual_symptom_medical_care_visited_doctor",
    "pct_unusual_symptom_medical_care_urgent_care",
    "pct_unusual_symptom_medical_care_er",
    "pct_unusual_symptom_medical_care_hospital",
    "pct_unusual_symptom_medical_care_tried",
    "pct_unusual_symptom_tested",
    "pct_unusual_symptom_tested_positive"
  ),
  "behavior_and_mental_health" = c(
    "pct_large_event_1d",
    "pct_mask_large_event_1d",
    "pct_mask_public_transit_1d",
    "pct_mask_restaurant_1d",
    "pct_mask_shop_1d",
    "pct_mask_spent_time_1d",
    "pct_mask_shop_indoors_1d",
    "pct_mask_restaurant_indoors_1d",
    "pct_mask_spent_time_indoors_1d",
    "pct_mask_large_event_indoors_1d",
    "pct_mask_work_outside_home_1d",
    "pct_mask_work_outside_home_indoors_1d",
    "pct_public_transit_1d",
    "pct_shop_1d",
    "pct_spent_time_1d",
    "pct_restaurant_1d",
    "pct_shop_indoors_1d",
    "pct_restaurant_indoors_1d",
    "pct_spent_time_indoors_1d",
    "pct_large_event_indoors_1d",
    "pct_travel_outside_state_5d",
    "pct_travel_outside_state_7d",
    "pct_work_outside_home_1d",
    "pct_work_outside_home_indoors_1d",
    "pct_work_outside_home_5d",
    "pct_anxious_5d",
    "pct_anxious_5d_alt",
    "pct_anxious_7d",
    "pct_anxious_7d_alt",
    "pct_depressed_5d",
    "pct_depressed_5d_alt",
    "pct_depressed_7d",
    "pct_depressed_7d_alt",
    "pct_felt_isolated_5d",
    "pct_felt_isolated_5d_alt",
    "pct_felt_isolated_7d",
    "pct_felt_isolated_7d_alt",
    "pct_delayed_care_cost",
    "pct_race_treated_fairly_healthcare",
    "pct_worried_become_ill",
    "pct_direct_contact",
    "pct_finance",
    "pct_wearing_mask_5d",
    "pct_wearing_mask_5d_alt",
    "pct_wearing_mask_7d",
    "pct_wearing_mask_7d_alt",
    "pct_others_masked",
    "pct_others_masked_alt",
    "pct_avoid_contact",
    "pct_avoid_contact_7d",
    "pct_covid_vaccinated_friends_alt",
    "pct_depressed_7d_alt",
    "pct_direct_contact_covid",
    "pct_direct_contact_covid_hh",
    "pct_finance_alt",
    "pct_financial_threat",
    "pct_others_distanced_public_alt",
    "pct_others_masked_public",
    "pct_others_masked_public_alt",
    "pct_wearing_mask_7d_alt",
    "pct_work_healthcare_5d",
    "pct_work_nursing_home_5d",
    "pct_work_outside_home_4w",
    "pct_work_outside_home_5d"
  ),
  "norms_information_beliefs" = c(
    "pct_belief_children_immune",
    "pct_belief_created_small_group",
    "pct_belief_distancing_effective",
    "pct_belief_govt_exploitation",
    "pct_belief_masking_effective",
    "pct_belief_vaccinated_mask_unnecessary",
    "pct_covid_vaccinated_friends",
    "pct_others_distanced_public",
    "pct_others_masked_public",
    "pct_received_news_experts",
    "pct_received_news_friends",
    "pct_received_news_govt_health",
    "pct_received_news_journalists",
    "pct_received_news_local_health",
    "pct_received_news_none",
    "pct_received_news_politicians",
    "pct_received_news_religious",
    "pct_received_news_cdc",
    "pct_want_info_children_education",
    "pct_want_info_covid_treatment",
    "pct_want_info_covid_variants",
    "pct_want_info_employment",
    "pct_want_info_mental_health",
    "pct_want_info_none",
    "pct_want_info_relationships",
    "pct_want_info_vaccine_access",
    "pct_want_info_vaccine_types",
    "pct_worried_catch_covid"
  ),
  "parenting" = c(
    "pct_child_school_homeschool",
    "pct_child_school_not",
    "pct_child_school_other",
    "pct_child_school_private",
    "pct_child_school_public",
    "pct_child_vaccine_already",
    "pct_child_vaccine_no_def",
    "pct_child_vaccine_no_prob",
    "pct_child_vaccine_vaccinated_or_accept",
    "pct_child_vaccine_yes_def",
    "pct_child_vaccine_yes_prob",
    "pct_has_child_under_18",
    "pct_oldest_child_under_5",
    "pct_oldest_child_12_to_15",
    "pct_oldest_child_16_to_17",
    "pct_oldest_child_5_to_11",
    "pct_children_gr1_5",
    "pct_children_gr6_8",
    "pct_children_gr9_12",
    "pct_children_prek",
    "pct_children_school_measure_cafeteria",
    "pct_children_school_measure_class_size",
    "pct_children_school_measure_desk_shield",
    "pct_children_school_measure_desk_space",
    "pct_children_school_measure_entry",
    "pct_children_school_measure_extracurricular",
    "pct_children_school_measure_mask_students",
    "pct_children_school_measure_mask_teachers",
    "pct_children_school_measure_outdoor",
    "pct_children_school_measure_playground",
    "pct_children_school_measure_same_students",
    "pct_children_school_measure_same_teacher",
    "pct_children_school_measure_screening",
    "pct_children_school_measure_supplies",
    "pct_inperson_school_fulltime",
    "pct_inperson_school_parttime",
    "pct_school_safety_measures_mask_students",
    "pct_school_safety_measures_mask_teachers",
    "pct_school_safety_measures_restricted_entry",
    "pct_school_safety_measures_separators",
    "pct_school_safety_measures_extracurricular",
    "pct_school_safety_measures_symptom_screen",
    "pct_school_safety_measures_ventilation",
    "pct_school_safety_measures_testing_staff",
    "pct_school_safety_measures_testing_students",
    "pct_school_safety_measures_vaccine_staff",
    "pct_school_safety_measures_vaccine_students",
    "pct_school_safety_measures_cafeteria",
    "pct_school_safety_measures_dont_know",
    "pct_remote_school_fulltime_oldest",
    "pct_inperson_school_fulltime_oldest",
    "pct_inperson_school_parttime_oldest",
    "pct_vaccinate_children",
    "pct_child_vaccine_vaccinated_or_accept"
  )
)

receiving_dir <- "contingency_receiving"
old_comparison_dir <- ""
filepaths <- list.files(receiving_dir, full_path = TRUE)
filenames <- list.files(receiving_dir, full_path = FALSE)
names(filepaths) <- filenames

for (file in names(filepaths)) {
  path <- filepaths[file]
  data <- read_csv(path)

  # Sample size columns reflect the new reporting threshold of 40 with rounding to the nearest 5.
  ss_df <- select(data, contains("sample_size_"))
  if (!(min(ss_df, na.rm=TRUE) >= 40)) {
    warning("file ", path, " has a min sample size less than 40")
  }
  list_remainder = unlist(as.list(as.matrix(ss_df %% 5)))
  if (!all(list_remainder == 0 | is.na(list_remainder)) ) {
    warning("file ", path, " contains sample sizes that have not been rounded to a multiple of 5")
  }

  if (grepl("theme", file)) {
      # In ‘theme’ tables, only the indicators that correspond to the ‘theme’ are there.
    for (theme in names(THEME_GROUPS)) {
      if (grepl(theme, file)) {
      val_df <- select(data, contains("val_"), contains("sample_size_"), contains("se_"), contains("represented_"), contains("sd_"),   contains("p25_"), contains("p50_"), contains("p75_"))
        val_df <- select(val_df, -contains(THEME_GROUPS[[theme]]))
        if (ncol(val_df) != 0) {
          warning("file ", path, " contains columns ", names(val_df), " not in the theme group")
        }
      }
    }
  } else {
    old_file <- file.path(old_comparison_dir, str_replace(file, "_all_indicators", ""))
    if (file.exists(old_file)) {
      old_data <- read_csv(old_file)

      # Subset data to shared columns.
      shared_fields <- intersect(names(data), names(old_data))
      new_subset <- select(data, shared_fields)
      old_subset <- select(old_data, shared_fields)

      # Subset data to shared groups and sort by grouping vars.
      value_names <- select(data[1,], contains("val_"), contains("sample_size_"), contains("se_"), contains("represented_"), contains("sd_"),   contains("p25_"), contains("p50_"), contains("p75_")) %>% names()
      group_names <- setdiff(names(old_subset), c(value_names, "issue_date"))
      in_old_df <- select(old_subset, !!!group_names) %>% mutate(in_old_df = TRUE)

      new_subset <- left_join(new_subset, in_old_df, on = group_names) %>%
        filter(in_old_df) %>%
        select(-in_old_df) %>%
        arrange(group_names)
      old_subset <- arrange(old_subset, group_names)

      if (dim(new_subset) != dim(old_subset)) {
        warning("file ", path, " has different dimensions than old version ", old_file)
        print("new dimensions")
        print(dim(new_subset))
        print("old dimensions")
        print(dim(old_subset))
      } else {
        # The proportion of “NA” cells should be lower (or equal to) in the newer version than in
        # the older version, given the lower reporting threshold.
        if (!(sum(is.na(new_subset))/(nrow(new_subset) * ncol(new_subset)) <= sum(is.na(old_subset))/(nrow(old_subset) * ncol(old_subset)))) {
          warning("file ", path, " has higher missingness than old version ", old_file)
        }

        # For indicator cells/values that wouldn’t have changed, make sure that the indicator
        # cell values are the same across the old version and new version.
        #
        # Cells aren't expected to change if:
        #  - sample size in old data is not missing (>= 100), regardless of what value new version has in the corresponding cell
        #  - not sample size field
        #  - not se field
        #  - not associated with a mean (so no sd, p25, p50, p75 fields)
        #  - column is also in old version
        new_subset <- select(new_subset,
          -contains("sample_size_"),
          -contains("se_"),
          -contains("sd_"),
          -contains("p25_"),
          -contains("p50_"),
          -contains("p75_")
        )
        old_subset <- select(old_subset,
          -contains("sample_size_"),
          -contains("se_"),
          -contains("sd_"),
          -contains("p25_"),
          -contains("p50_"),
          -contains("p75_")
        )
        #
        new_subset <- replace(new_subset, is.na(old_subset), NA)
        old_subset <- replace(old_subset, is.na(old_subset), NA)

        diff_elem <- which(new_subset != old_subset)
        if (length(diff_elem) != 0) {
          warning(
            "file ", path, " and old version ", old_file,
            " have different values for some cells that shouldn't have changed"
          )
          print("locations of differing values")
          print(head(diff_elem))
        }
      }
    }
  }

}