"""Registry for constants."""
from datetime import timedelta

from delphi_utils import Smoother

# global constants
METRICS = [#"Abdominal pain",
           "Anosmia",
           "Ageusia",
           "Acute bronchitis",
           "Asthma",
           "Bronchitis",
           "Chills",
           #"Cluster headache",
           "Common cold",
           "Cough",
           "Crackles",
           "Croup",
           #"Diarrhea",
           #"Dizziness",
           "Dysgeusia",
           #"Fatigue",
           "Fever",
           #"Headache",
           "Hyperthermia",
           #"Indigestion",
           "Laryngitis",
           #"Lightheadedness",
           "Low grade fever",
           #"Migraine",
           #"Muscle weakness",
           #"Myalgia",
           #"Nausea",
           "Nasal congestion",
           #"Night sweats",
           #"Pain",
           #"Perspiration",
           "Phlegm",
           "Pneumonia",
           "Post nasal drip",
           "Rhinitis",
           "Rhinorrhea",
           "Shivering",
           "Shortness of breath",
           "Sinusitis",
           "Sore throat",
           "Sputum",
           "Throat irritation",
           "Upper respiratory tract infection",
           #"Vomiting",
           #"Weakness",
           "Wheeze",
           #"hyperhidrosis",
           "Type 2 diabetes",
           "Urinary tract infection",
           "Hair loss",
           "Candidiasis",
           "Weight gain"]

COMBINED_METRIC = ["s01", "s02", "s03",
                   #"s04",
                   "s05", "s06",
                   #"s07",
                   "s08",
                   #"s09", "s10",
                   "scontrol"]

SYMPTOM_SETS = {
    "s01": ["Cough", "Phlegm", "Sputum", "Upper respiratory tract infection"],
    "s02": ["Nasal congestion", "Post nasal drip", "Rhinorrhea", "Sinusitis",
            "Rhinitis", "Common cold"],
    "s03": ["Fever", "Hyperthermia", "Chills", "Shivering", "Low grade fever"],
    #"s04": ["Fatigue", "Weakness", "Muscle weakness", "Myalgia", "Pain"],
    "s05": ["Shortness of breath", "Wheeze", "Croup", "Pneumonia", "Asthma",
            "Crackles", "Acute bronchitis", "Bronchitis"],
    "s06": ["Anosmia", "Dysgeusia", "Ageusia"],
    #"s07": ["Nausea", "Vomiting", "Diarrhea", "Indigestion", "Abdominal pain"],
    "s08": ["Laryngitis", "Sore throat", "Throat irritation"],
    #"s09": ["Headache", "Migraine", "Cluster headache", "Dizziness", "Lightheadedness"],
    #"s10": ["Night sweats","Perspiration", "hyperhidrosis"],
    "scontrol": ["Type 2 diabetes", "Urinary tract infection", "Hair loss",
                 "Candidiasis", "Weight gain"]
}


SMOOTHERS = ["raw", "smoothed"]
GEO_RESOLUTIONS = [
    "state",
    "county",
    "msa",
    "hrr",
    "hhs",
    "nation"
]

SMOOTHERS_MAP = {
    "raw":               (Smoother("identity", impute_method=None),
                          lambda d: d - timedelta(days=7)),
    "smoothed":          (Smoother("moving_average", window_length=7,
                                   impute_method='zeros'), lambda d: d)
}



STATE_TO_ABBREV = {'Alabama': 'al',
                   'Alaska': 'ak',
                   #                   'American Samoa': 'as',
                   'Arizona': 'az',
                   'Arkansas': 'ar',
                   'California': 'ca',
                   'Colorado': 'co',
                   'Connecticut': 'ct',
                   'Delaware': 'de',
                   #                   'District of Columbia': 'dc',
                   'Florida': 'fl',
                   'Georgia': 'ga',
                   #                   'Guam': 'gu',
                   'Hawaii': 'hi',
                   'Idaho': 'id',
                   'Illinois': 'il',
                   'Indiana': 'in',
                   'Iowa': 'ia',
                   'Kansas': 'ks',
                   'Kentucky': 'ky',
                   'Louisiana': 'la',
                   'Maine': 'me',
                   'Maryland': 'md',
                   'Massachusetts': 'ma',
                   'Michigan': 'mi',
                   'Minnesota': 'mn',
                   'Mississippi': 'ms',
                   'Missouri': 'mo',
                   'Montana': 'mt',
                   'Nebraska': 'ne',
                   'Nevada': 'nv',
                   'New_Hampshire': 'nh',
                   'New_Jersey': 'nj',
                   'New_Mexico': 'nm',
                   'New_York': 'ny',
                   'North_Carolina': 'nc',
                   'North_Dakota': 'nd',
                   #                   'Northern Mariana Islands': 'mp',
                   'Ohio': 'oh',
                   'Oklahoma': 'ok',
                   'Oregon': 'or',
                   'Pennsylvania': 'pa',
                   #                   'Puerto Rico': 'pr',
                   'Rhode_Island': 'ri',
                   'South_Carolina': 'sc',
                   'South_Dakota': 'sd',
                   'Tennessee': 'tn',
                   'Texas': 'tx',
                   'Utah': 'ut',
                   'Vermont': 'vt',
                   #                   'Virgin Islands': 'vi',
                   'Virginia': 'va',
                   'Washington': 'wa',
                   'West_Virginia': 'wv',
                   'Wisconsin': 'wi',
                   'Wyoming': 'wy'}

DC_FIPS = "11001"
