"""Registry for constants."""
from functools import partial
from datetime import timedelta

from .smooth import (
    identity,
    kday_moving_average,
)

# global constants
METRICS = ["Abdominal pain",
           "Anosmia",
           "Ageusia",
           "Acute bronchitis",
           "Allergy",
           "Amnesia",
           "Anaphylaxis",
           "Arthralgia",
           "Asthma",
           "Back pain",
           "Breast pain",
           "Bronchitis",
           "Burning chest pain",
           "Chest pain",
           "Chills",
           "Cluster headache",
           "Common cold",
           "Cough",
           "Crackles",
           "Crepitus",
           "Croup",
           "Diarrhea",
           "Dizziness",
           "Dysgeusia",
           "Dysphagia",
           "Encephalitis",
           "Excessive daytime sleepiness",
           "Fatigue",
           "Fever",
           "Globus pharyngis",
           "Goitre",
           "Headache",
           "Hives",
           "Hypercapnia",
           "Hyperthermia",
           "Indigestion",
           "Laryngitis",
           "Lightheadedness",
           "Low grade fever",
           "Migraine",
           "Muscle weakness",
           "Myalgia",
           "Nausea",
           "Nasal congestion",
           "Night sweats",
           "Orthostatic hypotension",
           "Pain",
           "Palpitations",
           "Perspiration",
           "Phlegm",
           "Pneumonia",
           "Post nasal drip",
           "Pulmonary edema",
           "Rheum",
           "Rhinitis",
           "Rhinorrhea",
           "Shallow breathing",
           "Sharp pain",
           "Shivering",
           "Shortness of breath",
           "Sinusitis",
           "Sleep deprivation",
           "Sleep disorder",
           "Sore throat",
           "Sputum",
           "Throat irritation",
           "Tonsillitis",
           "Upper respiratory tract infection",
           "Viral pneumonia",
           "Vomiting",
           "Weakness",
           "Wheeze",
           "hyperhidrosis",
           "Type 2 diabetes",
           "Urinary tract infection",
           "Hair loss",
           "Candidiasis",
           "Weight gain"]

COMBINED_METRIC = ["sum_anosmia_ageusia", "S01", "S02", "S03", "S04", "S05", "S06", "S07", "S08", "S09", "S10", "SControl"]

SYMPTOM_SETS = {
    "sum_anosmia_ageusia": ["Anosmia", "Ageusia"],
    "S01": ["Cough", "Phlegm", "Sputum", "Upper respiratory tract infection"],
    "S02": ["Nasal congestion", "Post nasal drip", "Rhinorrhea", "Sinusitis", "Rhinitis", "Common cold"],
    "S03": ["symptom_Fever", "symptom_Hyperthermia", "symptom_Chills", "symptom_Shivering", "symptom_Low_grade_fever"],
    "S04": ["symptom_Fatigue", "symptom_Weakness", "symptom_Muscle_weakness", "symptom_Myalgia", "symptom_Pain"],
    "S05": ["symptom_Shortness_of_breath", "symptom_Wheeze", "symptom_Croup", "symptom_Pneumonia", "symptom_Asthma", "symptom_Crackles", "symptom_Acute_bronchitis", "symptom_Bronchitis"],
    "S06": ["symptom_Anosmia", "symptom_Dysgeusia", "symptom_Ageusia"],
    "S07": ["symptom_Nausea", "symptom_Vomiting", "symptom_Diarrhea", "symptom_Indigestion", "symptom_Abdominal_pain"],
    "S08": ["symptom_Laryngitis", "symptom_Sore_throat", "symptom_Throat_irritation"],
    "S09": ["symptom_Headache", "symptom_Migraine", "symptom_Cluster_headache", "symptom_Dizziness", "symptom_Lightheadedness"],
    "S10": ["symptom_Night_sweats","symptom_Perspiration", "symptom_hyperhidrosis"],
    "SControl": ["symptom_Type_2_diabetes", "symptom_Urinary_tract_infection", "symptom_Hair_loss", "symptom_Candidiasis", "symptom_Weight_gain"]
}


SMOOTHERS = ["raw", "smoothed"]
GEO_RESOLUTIONS = [
    "state",
    "county",
    "msa",
    "hrr",
    "hhs",
    "nation"
]

seven_day_moving_average = partial(kday_moving_average, k=7)
SMOOTHERS_MAP = {
    "raw":           (identity, lambda d: d - timedelta(days=7)),
    "smoothed":      (seven_day_moving_average, lambda d: d),
}

STATE_TO_ABBREV = {'Alabama': 'al',
                   'Alaska': 'ak',
                   #                   'American Samoa': 'as',
                   'Arizona': 'az',
                   'Arkansas': 'ar',
                   'California': 'ca',
                   'Colorado': 'co',
                   'Connecticut': 'ct',
                   'Delaware': 'de',
                   #                   'District of Columbia': 'dc',
                   'Florida': 'fl',
                   'Georgia': 'ga',
                   #                   'Guam': 'gu',
                   'Hawaii': 'hi',
                   'Idaho': 'id',
                   'Illinois': 'il',
                   'Indiana': 'in',
                   'Iowa': 'ia',
                   'Kansas': 'ks',
                   'Kentucky': 'ky',
                   'Louisiana': 'la',
                   'Maine': 'me',
                   'Maryland': 'md',
                   'Massachusetts': 'ma',
                   'Michigan': 'mi',
                   'Minnesota': 'mn',
                   'Mississippi': 'ms',
                   'Missouri': 'mo',
                   'Montana': 'mt',
                   'Nebraska': 'ne',
                   'Nevada': 'nv',
                   'New_Hampshire': 'nh',
                   'New_Jersey': 'nj',
                   'New_Mexico': 'nm',
                   'New_York': 'ny',
                   'North_Carolina': 'nc',
                   'North_Dakota': 'nd',
                   #                   'Northern Mariana Islands': 'mp',
                   'Ohio': 'oh',
                   'Oklahoma': 'ok',
                   'Oregon': 'or',
                   'Pennsylvania': 'pa',
                   #                   'Puerto Rico': 'pr',
                   'Rhode_Island': 'ri',
                   'South_Carolina': 'sc',
                   'South_Dakota': 'sd',
                   'Tennessee': 'tn',
                   'Texas': 'tx',
                   'Utah': 'ut',
                   'Vermont': 'vt',
                   #                   'Virgin Islands': 'vi',
                   'Virginia': 'va',
                   'Washington': 'wa',
                   'West_Virginia': 'wv',
                   'Wisconsin': 'wi',
                   'Wyoming': 'wy'}

DC_FIPS = "11001"
