name: (Deprecated) Create Delphi Utils Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Semantic Version Number (i.e., 5.5.0 or patch, minor, major, prepatch, preminor, premajor, prerelease)'
        required: true
        default: patch

jobs:
  create_release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: _delphi_utils_python
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: prod
          ssh-key: ${{ secrets.CMU_DELPHI_DEPLOY_MACHINE_SSH }}
      - name: Reset prod branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Change version number
        id: version
        run: |
          python -m pip install bump2version
          echo -n "::set-output name=next_tag::"
          bump2version --list ${{ github.event.inputs.versionName }} | grep ^new_version | sed -r s,"^.*=",,
      - name: Create pull request into prod
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/${{ steps.version.outputs.next_tag }}
          commit-message: 'chore: release ${{ steps.version.outputs.next_tag }}'
          base: prod
          title: Release ${{ steps.version.outputs.next_tag }}
          labels: chore
          reviewers: krivard
          assignees: krivard
          body: |
            Releasing ${{ steps.version.outputs.next_tag }}.
